version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Pass@123
      WORDPRESS_DB_NAME: wordpressdb
    depends_on:
      - db
    volumes:
      - "wpwala:/var/www/html"
    networks:
      - mynetwork

  db:
    image: mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
      MYSQL_DATABASE: wordpressdb
    volumes:
      - "dbwala:/var/lib/mysql"
    networks:
      - mynetwork

volumes:
  wpwala:
  dbwala:

networks:
  mynetwork:
